### ISSUE TITLE
option : stride in bytes

### ISSUE THREAD

**Issue by AssociationSirius** [serge-rgb/TinyJPEG#3]
In stb_write_image, function have a 4° parameter: stride_in_bytes

int stbi_write_png(char const *filename, int w, int h, int comp, const void *data, int stride_in_bytes);

so writing 

unsigned char* buffer = (unsigned char*)malloc (width * height * 3);
glReadPixels (0, 0, width, height, GL_RGB, GL_UNSIGNED_BYTE, buffer);
unsigned char* last_row = buffer + (width * 3 * (height - 1));
stbi_write_png (name, width, height, 3, last_row, -3 * width)

There is no need to flip the image OpenGL.

could it have on tje_encode_to_file_at_quality a fourth identical parameter?

**Comment by serge-rgb** [comment]
I'm not against adding support for a stride parameter, but unless it is something that a lot of people want, I don't think that the increase in API complexity is worth it. 

But in your particular case, the change needed to flip the image is only a couple of lines.

I created a gist called tiny_jpeg_flipped.h that flips the image by default. Hopefully it will help. https://gist.github.com/serge-rgb/61248241d2197e3d98c1
Take a look at lines 1030 to 1050. It's just reversing the direction of y and also reversing the orientation of the 8x8 blocks. 
Again, the cost of increasing the API surface area to add a flipped version is too much. It's a small change for anyone who wants it though, so if this issue comes up again, I can point them here.

Your image re-encoded with tiny_jpeg_flipped.h
![out](https://cloud.githubusercontent.com/assets/282970/10679083/e28bd7f6-78db-11e5-8bec-5b2f0cee1485.jpg)

**Comment by AssociationSirius** [comment]
Thank you !
I will study your file and compare it to the original file to understand your work and be able to use OpenGL easily.

**Comment by serge-rgb** [comment]
No problem :)

Please let me know if you have any questions
